AWSTemplateFormatVersion: '2010-09-09'
Description: S3 bucket template

Parameters:
  BucketName:
    Type: String
    Description: S3 Bucket Name

Resources:
  MyBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName